[build.environment]
  PNPM_FLAGS = "--shamefully-hoist"

[build]
  command = "pnpm run build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[redirects]]
  from = "https://scan.angelakohrs.de"
  to = "https://angelakohrs.de"
  status = 301
  force = true
  headers = {X-From = "Scan Subdomain"}

[[redirects]]
  from = "https://heilpraktikerin.angelakohrs.de"
  to = "https://angelakohrs.de"
  status = 301
  force = true
  headers = {X-From = "Heilpraktikerin Subdomain"}

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"